### ISSUE TITLE
How-to get a claim guid

### ISSUE THREAD

**Issue by mwtoews** [maxlath/wikibase-edit#33]
The How-to guide describes `wdEdit.claim.add`, which works wonderfully. However, to add qualifiers and references for this claim, a GUID is required. The How-to shows a `const claimGuid` declaration, but does not demonstrate how to get the `claimGuid` for a claim. An example to get this dynamically would be appreciated.

Also, the how-to uses `const claimGuid`, but uses a different name, `guid`, in some of the functions. This is possibly an error, as these functions should use `claimGuid`.

**Comment by maxlath** [comment]
hi, sorry for the delayed answer, this somehow got out of my radar ^^

but I have some good news!
* there is now a section in the documentation on [how to get a claim guid](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#how-to-get-a-claim-guid) (7bf317c)
* the variable name `claimGuid` was removed from the documentation to avoid confusion (e267e08)
* but in your use-case, since `v4.6.0`, maybe you don't need to get the claim guid anymore: qualifiers and references can directly be added from `wbEdit.claim.add` \o/ (or rather from [`wbEdit.claim.create`](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#create-claim) as we now prefer to call it)
